name: Keep Render Awake

on:
  schedule:
    - cron: "*/10 * * * *"  # каждые 10 минут
  workflow_dispatch:        # можно запустить вручную из интерфейса

jobs:
  ping-render:
    runs-on: ubuntu-latest

    steps:
      - name: Curl ping to Render URL
        run: curl -m 10 --retry 3 ${{ secrets.RENDER_PING_URL }}