name: Keep Render Awake

on:
  schedule:
    - cron: '*/10 * * * *'  # каждые 10 минут
  workflow_dispatch:        # ручной запуск из интерфейса

jobs:
  ping:
    runs-on: ubuntu-latest
    steps:
      - name: Ping Render Health Check
        run: curl -s https://rezon-voice-bot.onrender.com/health || echo "Ping failed"